version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:  
  minio:
    driver: local  

services:
### Minio ################################################
    minio:
      container_name: minio-treinamento-2022
      build: ./minio
      volumes:
        #- /home/data/sftpdeveloper:/data
        - ${DATA_PATH_HOST}/minio/data:/export
        - ${DATA_PATH_HOST}/minio/config:/root/.minio
      ports:
        - "${MINIO_PORT}:9000"
        - "${MINIO_CONSOLE_PORT}:9001"
      environment:
        - MINIO_ROOT_USER=${MINIO_ROOT_USER}
        - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      networks:
        - frontend
        - backend

